name: CI
on:
  pull_request:
    branches: [main]
    paths:
      - '**.tf'
      
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    # Runs a single command using the runners shell
    - name: Webhook
      uses: distributhor/workflow-webhook
      with:
        url: "https://1b9e-2a00-23c7-2b8f-7301-c8ee-c415-5717-61b2.ngrok.io/pullRequestCreated"
        json: '{ "repository": "${{github.event.repository.full_name}}", "number": "${{github.event.number}}", "created_at": "${{github.event.pull_request.created_at}}", "updated_at": "${{github.event.pull_request.updated_at}}" }'
