name: CI
on:
  pull_request:
    branches: [main]
    paths:
      - '**.tf'
      
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    # Runs a single command using the runners shell
    - name: Webhook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_type: "json-extended"
        webhook_url: 'https://f4a3-2a00-23c7-2b8f-7301-10d4-f4d1-d649-3d2b.ngrok.io/pullRequestCreated'
        webhook_secret: 'aa'
        verbose: true
