name: CI
on:
  pull_request:
    branches: [main]
    paths:
      - '**.tf'
      
jobs:
  Trigger-ACR:
    runs-on: ubuntu-latest
    steps:
    - name: ACR Webhook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        verbose: true
